services:
  - type: web
    name: arduino-power-monitor
    env: node
    buildCommand: npm install
    startCommand: node bridge.js
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 